//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace info_app
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Klasa reprezentuj¹ca ulubione artyku³y u¿ytkownika.
    /// </summary>
    public partial class FavouriteAricles
    {
        /// <summary>
        /// Identyfikator u¿ytkownika.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// Identyfikator artyku³u.
        /// </summary>
        public int ArticleId { get; set; }

        /// <summary>
        /// Identyfikator ulubionego artyku³u.
        /// </summary>
        public int FavArt { get; set; }

        /// <summary>
        /// Artyku³ bêd¹cy ulubionym.
        /// </summary>
        public virtual Article Article { get; set; }

        /// <summary>
        /// U¿ytkownik, do którego nale¿y ulubiony artyku³.
        /// </summary>
        public virtual User User { get; set; }
    }
}

