//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace info_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Kontekst bazy danych dla aplikacji NewsApp.
    /// </summary>
    public partial class NewsAppDBEntities : DbContext
    {
        /// <summary>
        /// Konstruktor domyślny inicjujący nową instancję kontekstu bazy danych.
        /// </summary>
        public NewsAppDBEntities()
            : base("name=NewsAppDBEntities")
        {
        }

        /// <summary>
        /// Metoda wywoływana przy konfiguracji modelu bazy danych.
        /// </summary>
        /// <param name="modelBuilder">Builder modelu bazy danych.</param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// Zbiór danych dla artykułów.
        /// </summary>
        public virtual DbSet<Article> Article { get; set; }

        /// <summary>
        /// Zbiór danych dla ulubionych artykułów.
        /// </summary>
        public virtual DbSet<FavouriteAricles> FavouriteAricles { get; set; }

        /// <summary>
        /// Zbiór danych dla użytkowników.
        /// </summary>
        public virtual DbSet<User> User { get; set; }
    }
}

